admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9080 }

layered_runtime:
  layers:
  - name: static_layer_0
    static_layer:
      re2:
        max_program_size:
          error_level: 10000

overload_manager:
  actions:
  - name: envoy.overload_actions.shrink_heap
    triggers:
    - name: envoy.resource_monitors.fixed_heap
      threshold:
        value: 0.9
  - name: envoy.overload_actions.stop_accepting_requests
    triggers:
    - name: envoy.resource_monitors.fixed_heap
      threshold:
        value: 0.95
  refresh_interval:
    seconds: 0
    nanos: 250000000
  resource_monitors:
    - name: "envoy.resource_monitors.fixed_heap"
      typed_config:
        '"@type"': type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig
        max_heap_size_bytes: 2147483648
  actions:
    - name: "envoy.overload_actions.disable_http_keepalive"
      triggers:
        - name: "envoy.resource_monitors.fixed_heap"
          threshold:
            value: 0.95
    - name: "envoy.overload_actions.stop_accepting_requests"
      triggers:
        - name: "envoy.resource_monitors.fixed_heap"
          threshold:
            value: 0.99

static_resources:
  listeners:
    - name: listener_443
      address:
        socket_address: { address: 0.0.0.0, port_value: 443, protocol: TCP }
      filter_chains:
        - filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                '"@type"': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: tcp_443
                cluster: tcp_443
                access_log:
                - name: envoy.access_loggers.file
                  typed_config:
                    '"@type"': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: /var/log/envoy/tcp-443.access.443.log

    - name: listener_6443
      address:
        socket_address: { address: 0.0.0.0, port_value: 6443, protocol: TCP }
      filter_chains:
        - filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                '"@type"': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: tcp_6443
                cluster: tcp_6443
                access_log:
                - name: envoy.access_loggers.file
                  typed_config:
                    '"@type"': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: /var/log/envoy/tcp-6443.access.6443.log

    - name: listener_80
      address:
        socket_address: { address: 0.0.0.0, port_value: 80, protocol: TCP }
      filter_chains:
        - filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                '"@type"': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: tcp_80
                cluster: tcp_80
                access_log:
                - name: envoy.access_loggers.file
                  typed_config:
                    '"@type"': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: /var/log/envoy/tcp-80.access.80.log
  clusters:
  - name: tcp_443
    transport_socket:
      name: upstream_proxy_protocol
      typed_config:
        '"@type"': type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
        config:
          version: V1
        transport_socket:
          name: upstream_raw_buffer
          typed_config:
            '"@type"': type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
    connect_timeout: 5s
    per_connection_buffer_limit_bytes: 2048
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: tcp_443
      endpoints:
      - lb_endpoints:
$k8s_ingress_https

  - name: tcp_6443
    connect_timeout: 5s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: tcp_6443
      endpoints:
      - lb_endpoints:
$k8s_api_list

  - name: tcp_80
    transport_socket:
      name: upstream_proxy_protocol
      typed_config:
        '"@type"': type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
        config:
          version: V1
        transport_socket:
          name: upstream_raw_buffer
          typed_config:
            '"@type"': type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
    connect_timeout: 5s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: tcp_80
      endpoints:
      - lb_endpoints:
$k8s_ingress_http

  - name: prometheus_metrics
    connect_timeout: 5s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: prometheus_metrics
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 9080
